
n.sendMsg("/set/rateSlewTime", 0, 2.5);




n.sendMsg("/set/levelSlewTime", 0, 0.01);

n.sendMsg("/set/recLevel", 0, 0); n.sendMsg("/set/preLevel", 0, 1);
n.sendMsg("/set/recLevel", 0, 1); n.sendMsg("/set/preLevel", 0, 0.8);
n.sendMsg("/set/recLevel", 0, 0); n.sendMsg("/set/preLevel", 0, 1);
n.sendMsg("/set/recLevel", 0, 1); n.sendMsg("/set/preLevel", 0, 0.8);
n.sendMsg("/set/recLevel", 0, 0); n.sendMsg("/set/preLevel", 0, 1);
n.sendMsg("/set/recLevel", 0, 1); n.sendMsg("/set/preLevel", 0, 0.8);


n.sendMsg("/set/recLevel", 0, 1); n.sendMsg("/set/recFlag", 0, 0);
n.sendMsg("/set/recLevel", 0, 1); n.sendMsg("/set/recFlag", 0, 1);
n.sendMsg("/set/recLevel", 0, 1); n.sendMsg("/set/recFlag", 0, 0);
