function y = brickwall_butter8(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
% Generated on: 08-Nov-2018 17:20:55

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fpass = 12000;  % Passband Frequency
    % Fstop = 20000;  % Stopband Frequency
    % Apass = 1;      % Passband Ripple (dB)
    % Astop = 80;     % Stopband Attenuation (dB)
    % Fs    = 48000;  % Sampling Frequency
    %
    % h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'MatchExactly', 'stopband', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 2 1 1 0.275344278969942 0.677228354760348; 1 2 1 1 ...
        0.212096618412035 0.291962424933059; 1 2 1 1 0.180383753047887 ...
        0.0987871129257529; 1 2 1 1 0.166879821598983 0.0165294505854528], ...
        'ScaleValues', [0.488143158432572; 0.376014760836273; ...
        0.31979271649341; 0.295852318046109; 1]);
end

s = double(x);
y = step(Hd,s);

